config/routes.rb
Rails.application.routes.draw do
  

  root 'cars#index'

  
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :bookings
  resources :locations
  resources :cars
  resources :charges
  resources :reports
  resources :ratings

  resources :users do
    member do
      get :confirm_email
      get "dashboard" => "users#dashboard"
      get "pick_up" => "users#pick_up_car"
      get "choose_return_location" => "users#choose_return_location"
      get "returned_car" => "users#returned_car"
      get "set_return_location" => "users#set_return_location"
      get "history" => "users#history"
    end
  end
    
  resources :admins do
    member do
      get "dashboard"=> "admins#dashboard"
    end
  end

  get "login" => "sessions#new"
  get "admin-login" => "sessions#new_admin"
  get "register" => "users#new"
  get "logout" => "sessions#destroy"
  get "logoutadmin" => "sessions#destroy_admin"
  
  get "faq" => "footer#faq"
  get "about" => "footer#about"
  get "contact" => "footer#contact"
  
  get "profile" => "users#profile"
  get "topup" => "charges#new"
  
  get "car_list" => "cars#list"
  get "car_detail" => "cars#car_detail"
  get "cancel_booking" => "admins#cancel_booking"
    
  post "cancel_booking" => "admins#update_cancel_booking"
  post "login" => "sessions#create"
  post "admin-login" => "sessions#create_admin"
  
  
  
  
  
  
  

end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/cancel_booking.html.erb
<p id="notice"><%= notice %></p>

<div class="container border-bottom mb-3">
    <div class="row p-md-3">
        <span class="h1 col-4 offset-4 text-nowrap text-center">Cancel Booking</span>
    </div>
</div>

<div class="container">
    <form action="/cancel_booking" method="post">
        <input type="hidden" name="booking_id" value="<%= @booking.id %>"></input>
        
        
        <!--car location-->
        
        <div class="row justify-content-center">
            <strong class="col-md-3 col-4 align-middle pt-2 pb-2">Car Status:</strong>
            <select name="car_status">
                <option value="Unavailable" <%="selected=\"true\"" if Car.find(@booking.car_id).status == "Unavailable"%>>Unavailable</option>
                <option value="Available" <%="selected=\"true\"" if Car.find(@booking.car_id).status == "Available"%>>Available</option>
                <option value="Booked" <%="selected=\"true\"" if Car.find(@booking.car_id).status == "Booked"%>>Booked</option>
            </select>
        </div>
        
        <div class="row justify-content-center">
            <strong class="col-md-3 col-4 align-middle pt-2 pb-2">Pick Up Location Status:</strong>
            <select name="pickup_location_status">
                <option value = "Unavailable" <%="selected=\"true\"" if Location.find(@booking.pickup_location_id).status == "Unavailable"%>>Unavailable</option>
                <option value = "Available" <%="selected=\"true\"" if Location.find(@booking.pickup_location_id).status == "Available"%>>Available</option>
            </select>
        </div>
        
        <% if@booking.return_location_id %>
        <div class="row justify-content-center">
            <strong class="col-md-3 col-4 align-middle pt-2 pb-2">Return Location Status:</strong>
            <select name="return_location_status">
                <option></option>
                <option value="Unavailable" <%="selected=\"true\"" if Location.find(@booking.return_location_id).status == "Unavailable"%>>Unavailable</option>
                <option value="Available" <%="selected=\"true\"" if Location.find(@booking.return_location_id).status == "Available"%>>Available</option>
            </select>
        </div>
        <%end%>
        <input type="submit"></input>
    </form>
</div>

app/views/admins/dashboard.html.erb
<!--Chart.js-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js" integrity="sha256-J2sc79NPV/osLcIpzL3K8uJyAD7T5gaEFKlLDM18oxY=" crossorigin="anonymous"></script>

<div class="container border-bottom mb-3">
    <div class="row p-md-3">
        <span class="h3 col-12 text-nowrap text-center">Welcome, <%= current_admin.username %></span>
    </div>
</div>

<div>
    <% reports = Report.where(read: false) %>
    There are <%= reports.size %> unread reports <br>
</div>


<div class="container mb-3">
    <nav class="navbar navbar-light row justify-content-between">
      <button class="navbar-brand col-md-3 col-12 btn btn-light mb-3 bg-light">
        <i class="fas fa-car"></i>
          <%= link_to "Manage Cars", "/car_list"%>
      </button>
    
      <button class="navbar-brand col-md-3 col-12 btn btn-light mb-3 bg-light" href="#">
        <i class="fas fa-users"></i>
       <%= link_to "Manage Users", "/users"%>
      </button>
           
      <button class="navbar-brand col-md-3 col-12 btn btn-light mb-3 bg-light" href="#">
        <i class="fas fa-parking"></i>
       <%= link_to "Manage Location", "/locations"%>
      </button>
      
        <button class="navbar-brand col-md-3 col-12 btn btn-light mb-3 bg-light" href="#">
        <i class="fas fa-parking"></i>
       <%= link_to "Manage Bookings", "/bookings"%>
      </button>
      
        <button class="navbar-brand col-md-3 col-12 btn btn-light mb-3 bg-light" href="#">
        <i class="fas fa-parking"></i>
       <%= link_to "Manage Reports", "/reports"%>
      </button>
    </nav>
</div>

<nav class="container">
  <div class="nav nav-tabs row" id="nav-tab" role="tablist">
    <a class="nav-item nav-link active col-3" id="nav-weekly-tab" data-toggle="tab" href="#nav-weekly" role="tab" aria-controls="nav-weekly" aria-selected="true">Weekly</a>
    <a class="nav-item nav-link col-3" id="nav-monthly-tab" data-toggle="tab" href="#nav-monthly" role="tab" aria-controls="nav-monthly" aria-selected="false">Monthly</a>
    <a class="nav-item nav-link col-3" id="nav-quarterly-tab" data-toggle="tab" href="#nav-quarterly" role="tab" aria-controls="nav-quarterly" aria-selected="false">Quarterly</a>
    <a class="nav-item nav-link col-3" id="nav-yearly-tab" data-toggle="tab" href="#nav-yearly" role="tab" aria-controls="nav-yearly" aria-selected="false">Annualy</a>
  </div>
</nav>

<div class="container tab-content" id="nav-tabContent">
  <div class="tab-pane fade show active" id="nav-weekly" role="tabpanel" aria-labelledby="nav-weekly-tab">
    <canvas id="weekly" height="170"></canvas>
  </div>
  <div class="tab-pane fade" id="nav-monthly" role="tabpanel" aria-labelledby="nav-monthly-tab">
    <canvas id="monthly" height="170"></canvas>
  </div>
  <div class="tab-pane fade" id="nav-quarterly" role="tabpanel" aria-labelledby="nav-quarterly-tab">
    <canvas id="quarterly" height="170"></canvas>
  </div>
  <div class="tab-pane fade" id="nav-yearly" role="tabpanel" aria-labelledby="nav-yearly-tab">
    <canvas id="yearly" height="170"></canvas>
  </div>
</div>

<script>
var ctx = document.getElementById("weekly");
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        // labels: [<%#= @final_week_label %>],
        labels: ["Week <%= @weeks.keys[0] %>", "Week <%= @weeks.keys[1] %>", "Week <%= @weeks.keys[2] %>", "Week <%= @weeks.keys[3] %>", "Week <%= @weeks.keys[4] %>", "Week <%= @weeks.keys[5] %>", "Week <%= @weeks.keys[6] %>", "Week <%= @weeks.keys[7] %> (This Week)"],
        datasets: [{
            label: 'Income(AU Dollar)',
            data: [<%= @final_week_data %>],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)',
                'rgba(255, 159, 64, 0.2)',
                'rgba(153, 102, 255, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)',
                'rgba(255, 159, 64, 1)',
                'rgba(153, 102, 255, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>

<script>
var ctx = document.getElementById("monthly");
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ["January", "February", "March", "April", "May", "June","July","August","September", "October", "November", "December"],
        datasets: [{
            label: 'Income(AU Dollar)',
            data: [<%=@months[1]%>, <%=@months[2]%>, <%=@months[3]%>, <%=@months[4]%>, <%=@months[5]%>, <%=@months[6]%>, 
            <%=@months[7]%>, <%=@months[8]%>, <%=@months[9]%>, <%=@months[10]%>, <%=@months[11]%>, <%=@months[12]%>],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)',
                'rgba(255, 159, 64, 0.2)',
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)',
                'rgba(255, 159, 64, 1)',
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>

<script>
var ctx = document.getElementById("quarterly");
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ["Quarter 1", "Quarter 2", "Quarter 3", "Quarter 4",],
        datasets: [{
            label: 'Income(AU Dollar)',
            data: [<%=@quarters[1]%>, <%=@quarters[2]%>, <%=@quarters[3]%>, <%=@quarters[4]%>],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>

<script>
var ctx = document.getElementById("yearly");
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: [<%= @final_year_label %>],
        datasets: [{
            label: 'Income(AU Dollar)',
            data: [<%= @final_year_data %>],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admins</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.username %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @admin.username %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>