config/routes.rb
Rails.application.routes.draw do
  

  root 'cars#index'

  
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :bookings
  resources :locations
  resources :cars
  resources :charges
  resources :reports
  resources :ratings

  resources :users do
    member do
      get :confirm_email
      get "dashboard" => "users#dashboard"
      get "pick_up" => "users#pick_up_car"
      get "choose_return_location" => "users#choose_return_location"
      get "returned_car" => "users#returned_car"
      get "set_return_location" => "users#set_return_location"
      get "history" => "users#history"
    end
  end
    
  resources :admins do
    member do
      get "dashboard"=> "admins#dashboard"
    end
  end

  get "login" => "sessions#new"
  get "admin-login" => "sessions#new_admin"
  get "register" => "users#new"
  get "logout" => "sessions#destroy"
  get "logoutadmin" => "sessions#destroy_admin"
  
  get "faq" => "footer#faq"
  get "about" => "footer#about"
  get "contact" => "footer#contact"
  
  get "profile" => "users#profile"
  get "topup" => "charges#new"
  
  get "car_list" => "cars#list"
  get "car_detail" => "cars#car_detail"
  get "cancel_booking" => "admins#cancel_booking"
    
  post "cancel_booking" => "admins#update_cancel_booking"
  post "login" => "sessions#create"
  post "admin-login" => "sessions#create_admin"
  
  
  
  
  
  
  

end

app/models/rating.rb
class Rating < ActiveRecord::Base
    belongs_to :car
    belongs_to :user
 
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]
  before_action :authorize, only: [:new, :create, :show]
  before_action :admin_authorize, only: [:index, :update, :destroy]
  
  
  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all
  end
   

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
    
    @rating.user_id = current_user.id
    booking = current_user.current_booking
    @rating.booking_id = booking.id
    @rating.car_id= booking.car_id
    @ratingcar = Car.find(@rating.car_id)
    @ratingname = User.find(@rating.user_id)
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(rating_params)
   
    respond_to do |format|
      if @rating.save
        format.html { redirect_to "/users/"+current_user.id.to_s+"/dashboard", notice: 'Rating was successfully created.' }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :rating }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:user_id, :booking_id, :car_id, :rating, :time)
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div  class="container mt-3 pt-3 pb-2 border shadow">
  <h3>Enjoyed your ride?</h3>
    <p>Please be sure to rate your experience 1-5 stars! 1 stars being the worst and 5 stars being the best.</p>
    <div class="field">
      <%= f.hidden_field :user_id %>
    </div>
    <div class="field">
      <%= f.hidden_field :booking_id %>
    </div>  
    <div class="field">
      <%= f.hidden_field :car_id %>
    </div>
    
      <div class="row justify-content-md-center m-3">
        <%= f.label :rating, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-6">
          <%= f.number_field :rating, max: 5, min: 1, class: "form-control" %>
        </div>
      </div>
    
    <div class="field">
      <%= f.hidden_field :time %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class:"btn btn-primary btn-md col-4 offset-4 mt-3" %>
  
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ratings</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Booking</th>
      <th>Car</th>
      <th>Rating</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.user_id %></td>
        <td><%= rating.booking_id %></td>
        <td><%= rating.car_id %></td>
        <td><%= rating.rating %></td>
        <td><%= rating.time %></td>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<div class="container border-bottom mb-3">
    <div class="row p-md-3">
        <span class="h1 col-12 text-nowrap text-center">Rating</span>
    </div>
</div>

<%= render 'form' %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @rating.user_id %>
</p>

<p>
  <strong>Booking:</strong>
  <%= @rating.booking_id %>
</p>

<p>
  <strong>Car:</strong>
  <%= @rating.car_id %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @rating.rating %>
</p>

<p>
  <strong>Time:</strong>
  <%= @rating.time %>
</p>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>