config/routes.rb
Rails.application.routes.draw do
  

  root 'cars#index'

  
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :bookings
  resources :locations
  resources :cars
  resources :charges
  resources :reports
  resources :ratings

  resources :users do
    member do
      get :confirm_email
      get "dashboard" => "users#dashboard"
      get "pick_up" => "users#pick_up_car"
      get "choose_return_location" => "users#choose_return_location"
      get "returned_car" => "users#returned_car"
      get "set_return_location" => "users#set_return_location"
      get "history" => "users#history"
    end
  end
    
  resources :admins do
    member do
      get "dashboard"=> "admins#dashboard"
    end
  end

  get "login" => "sessions#new"
  get "admin-login" => "sessions#new_admin"
  get "register" => "users#new"
  get "logout" => "sessions#destroy"
  get "logoutadmin" => "sessions#destroy_admin"
  
  get "faq" => "footer#faq"
  get "about" => "footer#about"
  get "contact" => "footer#contact"
  
  get "profile" => "users#profile"
  get "topup" => "charges#new"
  
  get "car_list" => "cars#list"
  get "car_detail" => "cars#car_detail"
  get "cancel_booking" => "admins#cancel_booking"
    
  post "cancel_booking" => "admins#update_cancel_booking"
  post "login" => "sessions#create"
  post "admin-login" => "sessions#create_admin"
  
  
  
  
  
  
  

end

app/models/car.rb
class Car < ActiveRecord::Base
    has_many :bookings
    has_many :users, through: :bookings
    belongs_to :locations
    mount_uploader :image, ImageUploader
    has_many :ratings
    
    
     
    validates_presence_of :image, :make, :year, :model, :body_type, :number_plate, :condition, :price, :status, :location_id
    
    def deposit 
       self.price*7 
    end
    
    def name 
       self.year.to_s + " " + self.make.strip + " " + self.model.strip 
    end
    
   def rating
      if (!(self.ratings.pluck(:rating).inject{ |sum, el| sum + el }.to_f / self.ratings.size).nan?)
        (self.ratings.pluck(:rating).inject{ |sum, el| sum + el }.to_f / self.ratings.size).round
      else
          0
      end
   end
    
    # def self.search(body_type)
    #   if body_type
    #     where('body_type LIKE ?', "%#{body_type}%")
    #   else
    #     all
    #   end
    # end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy, :car_detail]

  before_action :admin_authorize, only: [:new, :edit, :create, :update, :destroy, :list]
  
  

  # GET /cars
  # GET /cars.json
  def index

    @cars = Car.all
    
    @cars = @cars.select{|car| car.status = 'Available'}
    
    if params[:body_type]
      @cars = @cars.select{|car| params[:body_type].include? car.body_type }
    end
    
    if params[:condition]
      @cars = @cars.select{|car| params[:condition].include? car.condition }
    end
    
    if params[:price] 
      @temp = Array.new
      
      params[:price].each do |price|
        case price
        when '0~50'
          @temp += @cars.select {|car| car.price <= 50 && car.price > 0}
        when '50~100'
          @temp += @cars.select {|car| car.price <= 100 && car.price > 50}
        when '100~150'
        @temp += @cars.select {|car| car.price <= 150 && car.price > 100}
        when '150~200'
        @temp += @cars.select {|car| car.price <= 200 && car.price > 150}
        when '200~∞'
        @temp += @cars.select {|car| car.price > 200}
        else
          
        end
      end
    end
    @cars = @temp if params[:price]
  end

  # GET /cars/1 
  # GET /cars/1.json
  def show
  end
  
  
  # GET /cars/new
  def new
    @car = Car.new
    @locations = Location.where(status: 'Available')
  end

  # GET /cars/1/edit
  def edit
    @locations = Location.where(status: 'Available')
    @locations << Location.find(@car.location_id) if @car.location_id
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      old_location = Location.find(@car.location_id)
      if @car.update(car_params)
        new_location = Location.find(@car.location_id)
        
        old_location.status = "Available"
        old_location.save
        
        new_location.status = "Unavailable"
        new_location.save
        
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def list
    @cars = Car.all
    if (params[:number_plate])
      @cars = @cars.select{|car| car.number_plate == params[:number_plate].strip}
    else
      @cars= Car.all
    end
  end
  
  def car_detail
    @bookings = @car.bookings
  end
  
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:image, :make, :year, :model, :body_type, :number_plate, :condition, :price, :location_id, :status)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/car_detail.html.erb
<p id="notice"><%= notice %></p>

<div class="container border-bottom mb-3">
    <div class="row p-md-3">
        <%#= link_to '<Back', cars_path,:class => 'small col-2 text-left align-middle pt-3 back-icon' -%>
        <span class="h1 col-4 offset-4 text-nowrap text-center">Car Details</span>
    </div>
</div>


<div class="row justify-content-center">
  <div class="row container">
    <div class="col-md-5 border" style="padding:1em">
      <%= image_tag(@car.image.url, alt: 'Car image', :class => "showImage") if @car.image? %>
    </div>
    
    <div class="col-md-7">
      
      <div class="row justify-content-center">
        <strong class="col-md-4 align-middle">Make:</strong>
        <p class="col-md-8 bg-light text-dark align-middle">
          <%= @car.make %>
        </p>
      </div>
      
      <div class="row justify-content-center">
        <strong class="col-md-4 align-middle">Year:</strong>
        <p class="col-md-8 bg-light text-dark align-middle">
          <%= @car.year %>
        </p>
      </div>
      
      <div class="row justify-content-center">
        <strong class="col-md-4 align-middle">Model:</strong>
        <p class="col-md-8 bg-light text-dark align-middle">
          <%= @car.model %>
        </p>
      </div>
      
      <div class="row justify-content-center">
        <strong class="col-md-4 align-middle">Body type:</strong>
        <p class="col-md-8 bg-light text-dark align-middle">
          <%= @car.body_type %>
        </p>
      </div>
      
      <div class="row justify-content-center">
        <strong class="col-md-4 align-middle">Number plate:</strong>
        <p class="col-md-8 bg-light text-dark align-middle">
          <%= @car.number_plate %>
        </p>
      </div>
      
      <div class="row justify-content-center">
        <strong class="col-md-4 align-middle">Condition:</strong>
        <p class="col-md-8 bg-light text-dark align-middle">
          <%= @car.condition %>
        </p>
      </div>
      
      <div class="row justify-content-center">
        <strong class="col-md-4 align-middle">Price:</strong>
        <p class="col-md-8 bg-light text-dark align-middle">
          <%= @car.price %>
        </p>
      </div>
      
      <div class="row justify-content-center">
        <strong class="col-md-4 align-middle">Status:</strong>
        <p class="col-md-8 bg-light text-dark align-middle">
          <%= @car.status %>
        </p>
      </div>
      
      <div class="row justify-content-center">
        <strong class="col-md-4 align-middle">Location:</strong>
        <p class="col-md-8 bg-light text-dark align-middle">
          &nbsp;<%= @car.location_id %>
        </p>
      </div>
      
      <div class="row justify-content-center">
        <strong class="col-md-4 align-middle">Rating:</strong>
        <p class="col-md-8 bg-light text-dark align-middle">
          
          <% 5.times do |i|  %>
            <% if i < @car.rating %>
              <span> <%=image_tag("star.png",size: "15")%></span>
            <% else %>
              <span> <%=image_tag("star_black.png",size: "15")%></span>
            <% end %>
          <% end %>
        </p>
      </div>
    </div>
  </div>

  <% if @bookings %>
    <div class="container row justify-content-center table-responsive mt-3">
      <table class="table table-hover">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Car</th>
            <th scope="col">User</th>
            <th scope="col">Pickup time</th>
            <th scope="col">Return time</th>
            <th scope="col">Pickup location</th>
            <th scope="col">Return location</th>
            <th scope="col">Status</th>
            <th colspan="2">Operation</th>
          </tr>
        </thead>
      
        <tbody>
          <% @bookings.each do |booking| %>
            <tr>
              <td><%= Car.find(booking.car_id).name if Car.exists?(id: booking.car_id) %></td>
              <td><%= User.find(booking.user_id).name if User.exists?(id: booking.user_id) %></td>
              <td><%= booking.pickup_time %></td>
              <td><%= booking.return_time %></td>
              <td><%= Location.find(booking.pickup_location_id).address if Location.exists?(id: booking.pickup_location_id) %></td>
              <td><%= Location.find(booking.return_location_id).address if Location.exists?(id: booking.return_location_id) %></td>
              <td><%= booking.status %></td>
              <td><%= link_to 'Show', booking, class: "btn btn-info btn-sm" %></td>
              <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
<% end %>
      
</div>

app/views/cars/edit.html.erb
<div class="container border-bottom mb-3">
    <div class="row p-md-3">
        <span class="h1 col-12 text-nowrap text-center">Editing Car</span>
    </div>
</div>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.1.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cars</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Make</th>
      <th>Year</th>
      <th>Model</th>
      <th>Body type</th>
      <th>Number plate</th>
      <th>Condition</th>
      <th>Price</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= image_tag(car.image.url, alt: 'Car image') if car.image? %></td>
        <td><%= car.make %></td>
        <td><%= car.year %></td>
        <td><%= car.model %></td>
        <td><%= car.body_type %></td>
        <td><%= car.number_plate %></td>
        <td><%= car.condition %></td>
        <td><%= car.price %></td>
        <td><%= car.status %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/index.html.2.erb
<p id="notice"><%= notice %></p>


<!--Search Bar-->

<div class="bg-secondary">
  <div class="container pt-2 pb-2">
    <div class="row">
      <div class="col-sm-4">
        <lable class="text-white">Location:</lable>
        <input class="form-control form-control-sm">
      </div>
      <div class="col-sm-4">
        <lable class="text-white">Start Time:</lable>
        <input class="form-control form-control-sm">
      </div>
      <div class="col-sm-3 offset-1 row justify-content-around m-1">
        <button class="btn btn-primary col-md-6 mt-1">
          Search
        </button>
        <button class="btn btn-info col-md-4 mt-1" type="button" data-toggle="collapse" data-target="#filterCollapse" aria-expanded="false" aria-controls="filterCollapse">
          Filter
        </button>
      </div>
    </div>
  </div>
  <div class="container collapse bg-secondary" id="filterCollapse">
    the filter options will be displayed here
  </div>
</div>

<!--Google Maps API-->
<div id="map" class="container-fluid mb-3"></div>


     <script>
  //   var map;
  //   function initMap() {
  //     map = new google.maps.Map(document.getElementById('map'), {
  //       center: {lat: -37.812148, lng: 144.967337},
  //       zoom: 13
  //     });
  //   }
    
   
      </script>

<!--<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyByZpeTDI3Rw0HIPNePOy67okhkSW1Oi3k&callback=initMap" async defer> </script>-->

  <script>
  // var labels = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
  //     var labelIndex = 0;
 function getJSONMarkers() {
          const markers = [
            {
              name:  "Rixos The Palm",
              location: [-37.812148, 144.867337]
            },
            {
              name:  "2",
              location: [-32.812148, 120.867337]
            },
            {
              name:  "3",
              location: [-30.812148, 110.867337]
            }
          ];
          return markers;
        }

        function initMap() {
          // Initialize Google Maps
          const mapOptions = {
            center:new google.maps.LatLng(-37.812148, 144.867337),
            zoom: 11
          }
          const map = new google.maps.Map(document.getElementById("map"), mapOptions);

          // Load JSON Data
          const hotelMarkers = getJSONMarkers();

          // Initialize Google Markers
          for(hotel of hotelMarkers) {
            let marker = new google.maps.Marker({
              map: map,
              position: new google.maps.LatLng(hotel.location[0], hotel.location[1]),
              title: hotel.name
            })
          }
        }


  

  </script>
  

  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyByZpeTDI3Rw0HIPNePOy67okhkSW1Oi3k&callback=initMap"
  async defer></script>






<!--thumbnail card-->
<div class="container">
  <div class="row">
    
    <% @cars.each do |car| %>
    
    <!--thumbnail card-->
      
    <div class="col-md-3">
    <a id="carCard" href="/cars/<%=car.id%>">
      <div class="card mb-4 shadow-sm">
        <img class="card-img-top" alt="Car image" src="assets/<%= "carDemo.jpg"%>" style="height: 225px; width: 100%; display: block;">
        <%= image_tag(car.image.url, alt: 'Car image') if car.image? %>
        <div class="card-body">
          <h5 class="font-weight-bold" style="line-height:0.5em;"><%= car.make %></h5>
          <h6 class="mb-3"><%= car.model %></h6>
          <p style="line-height:0.2em;">Year:<%= car.year %></p>
          <p style="line-height:0.2em;">Type:<%= car.body_type %></p>
          <p style="line-height:0.2em;">$<%= car.price %>/day</p>
          
        
          <% if(car.status.capitalize == "Available") %>
            <small class="text-success"><%= car.status %></small>
          <% else %>
            <small class="text-danger"><%= car.status %></small>
          <% end %>
        </div>
      </div>
    </a>
    </div>
    
    <% end %>
  </div>
</div>





<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/index.html.3.erb
<p id="notice"><%= notice %></p>


<!--Search Bar-->

<div class="bg-secondary">
  <div class="container pt-2 pb-2">
    <div class="row justify-content-between">
      <div class="col-md-4">
        <lable class="text-white">Location:</lable>
        <input class="form-control form-control-sm">
      </div>
      <div class="col-md-4">
        <lable class="text-white">Start Time:</lable>
        <input class="form-control form-control-sm">
      </div>
      <div class="col-md-3 offset-1 row justify-content-between m-1">
        <button class="btn btn-primary col-md-6 mt-1">
          Search
        </button>
        <button class="btn btn-info col-md-5 mt-1" type="button" data-toggle="collapse" data-target="#filterCollapse" aria-expanded="false" aria-controls="filterCollapse">
          Filter
        </button>
      </div>
    </div>
  </div>
  <div class="container collapse bg-secondary" id="filterCollapse">
    the filter options will be displayed here
  </div>
</div>

<!--Google Maps API-->
<div id="map" class="container-fluid mb-3"></div>


     <script>
  //   var map;
  //   function initMap() {
  //     map = new google.maps.Map(document.getElementById('map'), {
  //       center: {lat: -37.812148, lng: 144.967337},
  //       zoom: 13
  //     });
  //   }
    
   
      </script>

<!--<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyByZpeTDI3Rw0HIPNePOy67okhkSW1Oi3k&callback=initMap" async defer> </script>-->

  <script>
  // var labels = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
  //     var labelIndex = 0;
 function getJSONMarkers() {
          const markers = [
            {
              name:  "Rixos The Palm",
              location: [-37.812148, 144.867337]
            },
            {
              name:  "2",
              location: [-37.812148, 144.907337]
            },
            {
              name:  "3",
              location: [-37.822178, 144.935678]
            },
            {
              name:  "4",
              location: [-37.823458, 144.986543]
            },
            {
              name:  "5",
              location: [-37.834578, 144.934821]
            },
            {
              name:  "6",
              location: [-37.834558, 144.989456]
            },
            {
              name:  "7",
              location: [-37.812148, 144.967337]
            }
          ];
          return markers;
        }

        function initMap() {
          // Initialize Google Maps
          const mapOptions = {
            center:new google.maps.LatLng(-37.814148, 144.967337),
            zoom: 13
          }
          const map = new google.maps.Map(document.getElementById("map"), mapOptions);

          // Load JSON Data
          const hotelMarkers = getJSONMarkers();
          
          // Add marker image
          var carIcon = 'assets/<%= "carMarker.png"%>';
            
          // Initialize Google Markers
          for(hotel of hotelMarkers) {
            let marker = new google.maps.Marker({
              map: map,
              position: new google.maps.LatLng(hotel.location[0], hotel.location[1]),
              title: hotel.name,  //displays text when hover
              icon: carIcon   //variable of the mark image
            })
            
            //add mark event listener, open infowindow when click. 
            //just found methods from documentation. Not working perfectly. need to rewrite marker function
            marker.addListener('click', function () {
              var pos = new google.maps.LatLng(hotel.location[0], hotel.location[1]);
              infoWindow = new google.maps.InfoWindow;
              infoWindow.setPosition(pos);
              infoWindow.setContent('<h1 class="text-danger">Car info</h1>');
              infoWindow.open(map);  
            });
          }
        }


  

  </script>
  

  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyByZpeTDI3Rw0HIPNePOy67okhkSW1Oi3k&callback=initMap"
  async defer></script>






<!--display cars-->
<div class="container">
  <div class="row">
    
    <% @cars.each do |car| %>
    
    <!--thumbnail card-->
      
    <div class="col-md-3">
    <a id="carCard" href="/cars/<%=car.id%>">
      <div class="card mb-4 shadow-sm">
        <img class="card-img-top" alt="Car image" src="assets/<%= "carDemo.jpg"%>" style="height: 225px; width: 100%; display: block;">
        <%= image_tag(car.image.url, alt: 'Car image') if car.image? %>
        <div class="card-body">
          <h5 class="font-weight-bold" style="line-height:0.5em;"><%= car.make %></h5>
          <h6 class="mb-3"><%= car.model %></h6>
          <p style="line-height:0.2em;">Year:<%= car.year %></p>
          <p style="line-height:0.2em;">Type:<%= car.body_type %></p>
          <p style="line-height:0.2em;">$<%= car.price %>/day</p>
          
        
          <% if(car.status.capitalize == "Available") %>
            <small class="text-success"><%= car.status %></small>
          <% else %>
            <small class="text-danger"><%= car.status %></small>
          <% end %>
        </div>
      </div>
    </a>
    </div>
    
    <% end %>
  </div>
</div>





<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/list.html.erb
<p id="notice"><%= notice %></p>

<div class="container border-bottom mb-3">
    <div class="row p-md-3">
        <span class="h1 col-12 text-nowrap text-center">Manage Cars</span>
    </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="container row justify-content-between">
    <div class="col-md-8 col-12 pt-1 pb-1">
      <%= link_to 'Add a New Car', new_car_path, class: "btn btn-sm btn-secondary col-12" %>
    </div>
    <form class="row col-md-4 col-12 justify-content-between mb-2 ml-1 pt-1 pb-1">
      <input type="text" name="number_plate" class="form-control form-control-sm col-7" placeholder="Plate number"></input>
      <button type="submit" class="btn btn-secondary btn-sm col-4">Search</button>
    </form>
  </div>
</div>

<!--display cars-->
<div class="container">
  <div class="row">
    
    <% @cars.each do |car| %>
    
    <!--thumbnail card-->
      
    <div class="col-md-3">
      
      
      <div class="card mb-4 shadow-sm bg-light">
        <a id="carCard" href="/car_detail?id=<%=car.id%>" style="background-color: inherit; color: black; text-decoration:none">
            <%= image_tag(car.image.url, alt: 'Car image', :class => "carImage") if car.image? %>
            <div class="card-body">
              <h5 class="font-weight-bold" style="line-height:0.5em;"><%= car.make %></h5>
              <h6 class="mb-3"><%= car.model %></h6>
              <p style="line-height:0.2em;">Year:<%= car.year %></p>
                <p style="line-height:0.2em;">Type:<%= car.body_type %></p>
                <p style="line-height:0.2em;">$<%= car.price %>/day</p>
              
            
              <% if(car.status.capitalize == "Available") %>
                <small class="text-success"><%= car.status %></small>
              <% else %>
                <small class="text-danger"><%= car.status %></small>
              <% end %>
            </div>
        </a>
        <div class="row justify-content-between border-top ml-1 mr-1">
          <div class="col-6 text-center border-right pt-2 pb-2">
            <%= link_to 'Edit', edit_car_path(car), :class => "text-info carOprt" %>
          </div>
          <div class="col-6 text-center pt-2 pb-2">
            <%= link_to 'Delete', car, method: :delete, data: { confirm: 'Are you sure?' }, :class => "text-danger carOprt" %>
          </div>
        </div>
      </div>
      
      
    </div>
    
    <% end %>
  </div>
</div>

app/views/cars/new.html.erb
<div class="container border-bottom">
    <div class="row p-md-3">
        <%= link_to '<Back', cars_path,:class => 'small col-2 text-left align-middle pt-3 back-icon' -%>
        <span class="h1 col-4 offset-2 text-nowrap text-center">New Car</span>
    </div>
</div>

<%= render 'form' %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container border-bottom mb-3">
    <div class="row p-md-3">
        <%#= link_to '<Back', cars_path,:class => 'small col-2 text-left align-middle pt-3 back-icon' -%>
        <span class="h1 col-4 offset-4 text-nowrap text-center">Car Details</span>
    </div>
</div>


<div class="row justify-content-center">
  <div class="row col-md-8">
    <div class="col-md-5 border" style="padding:1em">
      <%= image_tag(@car.image.url, alt: 'Car image', :class => "showImage") if @car.image? %>
    </div>
    
    <div class="col-md-7">
      
      <div class="row justify-content-center">
        <strong class="col-md-4 align-middle">Make:</strong>
        <p class="col-md-8 bg-light text-dark align-middle">
          <%= @car.make %>
        </p>
      </div>
      
      <div class="row justify-content-center">
        <strong class="col-md-4 align-middle">Year:</strong>
        <p class="col-md-8 bg-light text-dark align-middle">
          <%= @car.year %>
        </p>
      </div>
      
      <div class="row justify-content-center">
        <strong class="col-md-4 align-middle">Model:</strong>
        <p class="col-md-8 bg-light text-dark align-middle">
          <%= @car.model %>
        </p>
      </div>
      
      <div class="row justify-content-center">
        <strong class="col-md-4 align-middle">Body type:</strong>
        <p class="col-md-8 bg-light text-dark align-middle">
          <%= @car.body_type %>
        </p>
      </div>
      
      <div class="row justify-content-center">
        <strong class="col-md-4 align-middle">Number plate:</strong>
        <p class="col-md-8 bg-light text-dark align-middle">
          <%= @car.number_plate %>
        </p>
      </div>
      
      <div class="row justify-content-center">
        <strong class="col-md-4 align-middle">Condition:</strong>
        <p class="col-md-8 bg-light text-dark align-middle">
          <%= @car.condition %>
        </p>
      </div>
      
      <div class="row justify-content-center">
        <strong class="col-md-4 align-middle">Price:</strong>
        <p class="col-md-8 bg-light text-dark align-middle">
          <%= @car.price %>
        </p>
      </div>
      
      <div class="row justify-content-center">
        <strong class="col-md-4 align-middle">Status:</strong>
        <p class="col-md-8 bg-light text-dark align-middle">
          <%= @car.status %>
        </p>
      </div>
      
      <div class="row justify-content-center">
        <strong class="col-md-4 align-middle">Location:</strong>
        <p class="col-md-8 bg-light text-dark align-middle">
          &nbsp;<%= @car.location_id %>
        </p>
      </div>
      
      <div class="row justify-content-center">
        <strong class="col-md-4 align-middle">Rating:</strong>
        <p class="col-md-8 bg-light text-dark align-middle">
          
          
          <%# if !@car.rating.nan? %>
          <% 5.times do |i|  %>
            <% if i < @car.rating %>
              <span> <%=image_tag("star.png",size: "15")%></span>
            <% else %>
              <span> <%=image_tag("star_black.png",size: "15")%></span>
            <% end %>
          <% end %>
          <%# end %>
          
          
        </p>
      </div>
      
  
    </div>
  
    <%= link_to "BOOK IT NOW", new_booking_path(:car => @car.id),:class => 'btn btn-primary btn-block mt-3' %>
  </div>
</div>